/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as IniciarSesionRouteImport } from './routes/iniciar-sesion'
import { Route as RecuperarContrasenaRouteImport } from './routes/recuperar-contrasena'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as RestablecerContrasenaRouteImport } from './routes/restablecer-contrasena'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCancelacionesRouteImport } from './routes/admin.cancelaciones'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminFinanzasRouteImport } from './routes/admin.finanzas'
import { Route as AdminPlanesRouteImport } from './routes/admin.planes'
import { Route as AdminSoporteRouteImport } from './routes/admin.soporte'
import { Route as EventosIndexRouteImport } from './routes/eventos.index'
import { Route as EventosEventIdRouteImport } from './routes/eventos.$eventId'
import { Route as EventosNuevoRouteImport } from './routes/eventos.nuevo'
import { Route as EventosSoporteRouteImport } from './routes/eventos.soporte'
import { Route as EventosSuscripcionRouteImport } from './routes/eventos.suscripcion'
import { Route as EventosWhatsappRouteImport } from './routes/eventos.whatsapp'
import { Route as PagoExitoRouteImport } from './routes/pago.exito'
import { Route as RegistroExitoRouteImport } from './routes/registro.exito'
import { Route as AdminSoporteIndexRouteImport } from './routes/admin.soporte.index'
import { Route as AdminSoporteTicketIdRouteImport } from './routes/admin.soporte.$ticketId'
import { Route as EventosEventIdIndexRouteImport } from './routes/eventos.$eventId.index'
import { Route as EventosEventIdAutomatizacionRouteImport } from './routes/eventos.$eventId.automatizacion'
import { Route as EventosEventIdConfiguracionRouteImport } from './routes/eventos.$eventId.configuracion'
import { Route as EventosEventIdConversacionesRouteImport } from './routes/eventos.$eventId.conversaciones'
import { Route as EventosEventIdEstadisticasRouteImport } from './routes/eventos.$eventId.estadisticas'
import { Route as EventosEventIdImportarRouteImport } from './routes/eventos.$eventId.importar'
import { Route as EventosEventIdInvitadosRouteImport } from './routes/eventos.$eventId.invitados'
import { Route as EventosEventIdListaFinalRouteImport } from './routes/eventos.$eventId.lista-final'
import { Route as EventosEventIdMensajesRouteImport } from './routes/eventos.$eventId.mensajes'
import { Route as EventosEventIdResumenRouteImport } from './routes/eventos.$eventId.resumen'
import { Route as EventosSoporteIndexRouteImport } from './routes/eventos.soporte.index'
import { Route as EventosSoporteTicketIdRouteImport } from './routes/eventos.soporte.$ticketId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const IniciarSesionRoute = IniciarSesionRouteImport.update({
  id: '/iniciar-sesion',
  path: '/iniciar-sesion',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarContrasenaRoute = RecuperarContrasenaRouteImport.update({
  id: '/recuperar-contrasena',
  path: '/recuperar-contrasena',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const RestablecerContrasenaRoute = RestablecerContrasenaRouteImport.update({
  id: '/restablecer-contrasena',
  path: '/restablecer-contrasena',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCancelacionesRoute = AdminCancelacionesRouteImport.update({
  id: '/cancelaciones',
  path: '/cancelaciones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanzasRoute = AdminFinanzasRouteImport.update({
  id: '/finanzas',
  path: '/finanzas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanesRoute = AdminPlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSoporteRoute = AdminSoporteRouteImport.update({
  id: '/soporte',
  path: '/soporte',
  getParentRoute: () => AdminRoute,
} as any)
const EventosIndexRoute = EventosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventosRoute,
} as any)
const EventosEventIdRoute = EventosEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => EventosRoute,
} as any)
const EventosNuevoRoute = EventosNuevoRouteImport.update({
  id: '/nuevo',
  path: '/nuevo',
  getParentRoute: () => EventosRoute,
} as any)
const EventosSoporteRoute = EventosSoporteRouteImport.update({
  id: '/soporte',
  path: '/soporte',
  getParentRoute: () => EventosRoute,
} as any)
const EventosSuscripcionRoute = EventosSuscripcionRouteImport.update({
  id: '/suscripcion',
  path: '/suscripcion',
  getParentRoute: () => EventosRoute,
} as any)
const EventosWhatsappRoute = EventosWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => EventosRoute,
} as any)
const PagoExitoRoute = PagoExitoRouteImport.update({
  id: '/pago/exito',
  path: '/pago/exito',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroExitoRoute = RegistroExitoRouteImport.update({
  id: '/exito',
  path: '/exito',
  getParentRoute: () => RegistroRoute,
} as any)
const AdminSoporteIndexRoute = AdminSoporteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSoporteRoute,
} as any)
const AdminSoporteTicketIdRoute = AdminSoporteTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => AdminSoporteRoute,
} as any)
const EventosEventIdIndexRoute = EventosEventIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventosEventIdRoute,
} as any)
const EventosEventIdAutomatizacionRoute =
  EventosEventIdAutomatizacionRouteImport.update({
    id: '/automatizacion',
    path: '/automatizacion',
    getParentRoute: () => EventosEventIdRoute,
  } as any)
const EventosEventIdConfiguracionRoute =
  EventosEventIdConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => EventosEventIdRoute,
  } as any)
const EventosEventIdConversacionesRoute =
  EventosEventIdConversacionesRouteImport.update({
    id: '/conversaciones',
    path: '/conversaciones',
    getParentRoute: () => EventosEventIdRoute,
  } as any)
const EventosEventIdEstadisticasRoute =
  EventosEventIdEstadisticasRouteImport.update({
    id: '/estadisticas',
    path: '/estadisticas',
    getParentRoute: () => EventosEventIdRoute,
  } as any)
const EventosEventIdImportarRoute = EventosEventIdImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => EventosEventIdRoute,
} as any)
const EventosEventIdInvitadosRoute = EventosEventIdInvitadosRouteImport.update({
  id: '/invitados',
  path: '/invitados',
  getParentRoute: () => EventosEventIdRoute,
} as any)
const EventosEventIdListaFinalRoute =
  EventosEventIdListaFinalRouteImport.update({
    id: '/lista-final',
    path: '/lista-final',
    getParentRoute: () => EventosEventIdRoute,
  } as any)
const EventosEventIdMensajesRoute = EventosEventIdMensajesRouteImport.update({
  id: '/mensajes',
  path: '/mensajes',
  getParentRoute: () => EventosEventIdRoute,
} as any)
const EventosEventIdResumenRoute = EventosEventIdResumenRouteImport.update({
  id: '/resumen',
  path: '/resumen',
  getParentRoute: () => EventosEventIdRoute,
} as any)
const EventosSoporteIndexRoute = EventosSoporteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventosSoporteRoute,
} as any)
const EventosSoporteTicketIdRoute = EventosSoporteTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => EventosSoporteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/eventos': typeof EventosRouteWithChildren
  '/iniciar-sesion': typeof IniciarSesionRoute
  '/recuperar-contrasena': typeof RecuperarContrasenaRoute
  '/registro': typeof RegistroRouteWithChildren
  '/restablecer-contrasena': typeof RestablecerContrasenaRoute
  '/admin/cancelaciones': typeof AdminCancelacionesRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/finanzas': typeof AdminFinanzasRoute
  '/admin/planes': typeof AdminPlanesRoute
  '/admin/soporte': typeof AdminSoporteRouteWithChildren
  '/eventos/$eventId': typeof EventosEventIdRouteWithChildren
  '/eventos/nuevo': typeof EventosNuevoRoute
  '/eventos/soporte': typeof EventosSoporteRouteWithChildren
  '/eventos/suscripcion': typeof EventosSuscripcionRoute
  '/eventos/whatsapp': typeof EventosWhatsappRoute
  '/pago/exito': typeof PagoExitoRoute
  '/registro/exito': typeof RegistroExitoRoute
  '/admin/': typeof AdminIndexRoute
  '/eventos/': typeof EventosIndexRoute
  '/admin/soporte/$ticketId': typeof AdminSoporteTicketIdRoute
  '/eventos/$eventId/automatizacion': typeof EventosEventIdAutomatizacionRoute
  '/eventos/$eventId/configuracion': typeof EventosEventIdConfiguracionRoute
  '/eventos/$eventId/conversaciones': typeof EventosEventIdConversacionesRoute
  '/eventos/$eventId/estadisticas': typeof EventosEventIdEstadisticasRoute
  '/eventos/$eventId/importar': typeof EventosEventIdImportarRoute
  '/eventos/$eventId/invitados': typeof EventosEventIdInvitadosRoute
  '/eventos/$eventId/lista-final': typeof EventosEventIdListaFinalRoute
  '/eventos/$eventId/mensajes': typeof EventosEventIdMensajesRoute
  '/eventos/$eventId/resumen': typeof EventosEventIdResumenRoute
  '/eventos/soporte/$ticketId': typeof EventosSoporteTicketIdRoute
  '/admin/soporte/': typeof AdminSoporteIndexRoute
  '/eventos/$eventId/': typeof EventosEventIdIndexRoute
  '/eventos/soporte/': typeof EventosSoporteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/iniciar-sesion': typeof IniciarSesionRoute
  '/recuperar-contrasena': typeof RecuperarContrasenaRoute
  '/registro': typeof RegistroRouteWithChildren
  '/restablecer-contrasena': typeof RestablecerContrasenaRoute
  '/admin/cancelaciones': typeof AdminCancelacionesRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/finanzas': typeof AdminFinanzasRoute
  '/admin/planes': typeof AdminPlanesRoute
  '/eventos/nuevo': typeof EventosNuevoRoute
  '/eventos/suscripcion': typeof EventosSuscripcionRoute
  '/eventos/whatsapp': typeof EventosWhatsappRoute
  '/pago/exito': typeof PagoExitoRoute
  '/registro/exito': typeof RegistroExitoRoute
  '/admin': typeof AdminIndexRoute
  '/eventos': typeof EventosIndexRoute
  '/admin/soporte/$ticketId': typeof AdminSoporteTicketIdRoute
  '/eventos/$eventId/automatizacion': typeof EventosEventIdAutomatizacionRoute
  '/eventos/$eventId/configuracion': typeof EventosEventIdConfiguracionRoute
  '/eventos/$eventId/conversaciones': typeof EventosEventIdConversacionesRoute
  '/eventos/$eventId/estadisticas': typeof EventosEventIdEstadisticasRoute
  '/eventos/$eventId/importar': typeof EventosEventIdImportarRoute
  '/eventos/$eventId/invitados': typeof EventosEventIdInvitadosRoute
  '/eventos/$eventId/lista-final': typeof EventosEventIdListaFinalRoute
  '/eventos/$eventId/mensajes': typeof EventosEventIdMensajesRoute
  '/eventos/$eventId/resumen': typeof EventosEventIdResumenRoute
  '/eventos/soporte/$ticketId': typeof EventosSoporteTicketIdRoute
  '/admin/soporte': typeof AdminSoporteIndexRoute
  '/eventos/$eventId': typeof EventosEventIdIndexRoute
  '/eventos/soporte': typeof EventosSoporteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/eventos': typeof EventosRouteWithChildren
  '/iniciar-sesion': typeof IniciarSesionRoute
  '/recuperar-contrasena': typeof RecuperarContrasenaRoute
  '/registro': typeof RegistroRouteWithChildren
  '/restablecer-contrasena': typeof RestablecerContrasenaRoute
  '/admin/cancelaciones': typeof AdminCancelacionesRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/finanzas': typeof AdminFinanzasRoute
  '/admin/planes': typeof AdminPlanesRoute
  '/admin/soporte': typeof AdminSoporteRouteWithChildren
  '/eventos/$eventId': typeof EventosEventIdRouteWithChildren
  '/eventos/nuevo': typeof EventosNuevoRoute
  '/eventos/soporte': typeof EventosSoporteRouteWithChildren
  '/eventos/suscripcion': typeof EventosSuscripcionRoute
  '/eventos/whatsapp': typeof EventosWhatsappRoute
  '/pago/exito': typeof PagoExitoRoute
  '/registro/exito': typeof RegistroExitoRoute
  '/admin/': typeof AdminIndexRoute
  '/eventos/': typeof EventosIndexRoute
  '/admin/soporte/$ticketId': typeof AdminSoporteTicketIdRoute
  '/eventos/$eventId/automatizacion': typeof EventosEventIdAutomatizacionRoute
  '/eventos/$eventId/configuracion': typeof EventosEventIdConfiguracionRoute
  '/eventos/$eventId/conversaciones': typeof EventosEventIdConversacionesRoute
  '/eventos/$eventId/estadisticas': typeof EventosEventIdEstadisticasRoute
  '/eventos/$eventId/importar': typeof EventosEventIdImportarRoute
  '/eventos/$eventId/invitados': typeof EventosEventIdInvitadosRoute
  '/eventos/$eventId/lista-final': typeof EventosEventIdListaFinalRoute
  '/eventos/$eventId/mensajes': typeof EventosEventIdMensajesRoute
  '/eventos/$eventId/resumen': typeof EventosEventIdResumenRoute
  '/eventos/soporte/$ticketId': typeof EventosSoporteTicketIdRoute
  '/admin/soporte/': typeof AdminSoporteIndexRoute
  '/eventos/$eventId/': typeof EventosEventIdIndexRoute
  '/eventos/soporte/': typeof EventosSoporteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/eventos'
    | '/iniciar-sesion'
    | '/recuperar-contrasena'
    | '/registro'
    | '/restablecer-contrasena'
    | '/admin/cancelaciones'
    | '/admin/clientes'
    | '/admin/finanzas'
    | '/admin/planes'
    | '/admin/soporte'
    | '/eventos/$eventId'
    | '/eventos/nuevo'
    | '/eventos/soporte'
    | '/eventos/suscripcion'
    | '/eventos/whatsapp'
    | '/pago/exito'
    | '/registro/exito'
    | '/admin/'
    | '/eventos/'
    | '/admin/soporte/$ticketId'
    | '/eventos/$eventId/automatizacion'
    | '/eventos/$eventId/configuracion'
    | '/eventos/$eventId/conversaciones'
    | '/eventos/$eventId/estadisticas'
    | '/eventos/$eventId/importar'
    | '/eventos/$eventId/invitados'
    | '/eventos/$eventId/lista-final'
    | '/eventos/$eventId/mensajes'
    | '/eventos/$eventId/resumen'
    | '/eventos/soporte/$ticketId'
    | '/admin/soporte/'
    | '/eventos/$eventId/'
    | '/eventos/soporte/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/iniciar-sesion'
    | '/recuperar-contrasena'
    | '/registro'
    | '/restablecer-contrasena'
    | '/admin/cancelaciones'
    | '/admin/clientes'
    | '/admin/finanzas'
    | '/admin/planes'
    | '/eventos/nuevo'
    | '/eventos/suscripcion'
    | '/eventos/whatsapp'
    | '/pago/exito'
    | '/registro/exito'
    | '/admin'
    | '/eventos'
    | '/admin/soporte/$ticketId'
    | '/eventos/$eventId/automatizacion'
    | '/eventos/$eventId/configuracion'
    | '/eventos/$eventId/conversaciones'
    | '/eventos/$eventId/estadisticas'
    | '/eventos/$eventId/importar'
    | '/eventos/$eventId/invitados'
    | '/eventos/$eventId/lista-final'
    | '/eventos/$eventId/mensajes'
    | '/eventos/$eventId/resumen'
    | '/eventos/soporte/$ticketId'
    | '/admin/soporte'
    | '/eventos/$eventId'
    | '/eventos/soporte'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/eventos'
    | '/iniciar-sesion'
    | '/recuperar-contrasena'
    | '/registro'
    | '/restablecer-contrasena'
    | '/admin/cancelaciones'
    | '/admin/clientes'
    | '/admin/finanzas'
    | '/admin/planes'
    | '/admin/soporte'
    | '/eventos/$eventId'
    | '/eventos/nuevo'
    | '/eventos/soporte'
    | '/eventos/suscripcion'
    | '/eventos/whatsapp'
    | '/pago/exito'
    | '/registro/exito'
    | '/admin/'
    | '/eventos/'
    | '/admin/soporte/$ticketId'
    | '/eventos/$eventId/automatizacion'
    | '/eventos/$eventId/configuracion'
    | '/eventos/$eventId/conversaciones'
    | '/eventos/$eventId/estadisticas'
    | '/eventos/$eventId/importar'
    | '/eventos/$eventId/invitados'
    | '/eventos/$eventId/lista-final'
    | '/eventos/$eventId/mensajes'
    | '/eventos/$eventId/resumen'
    | '/eventos/soporte/$ticketId'
    | '/admin/soporte/'
    | '/eventos/$eventId/'
    | '/eventos/soporte/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  EventosRoute: typeof EventosRouteWithChildren
  IniciarSesionRoute: typeof IniciarSesionRoute
  RecuperarContrasenaRoute: typeof RecuperarContrasenaRoute
  RegistroRoute: typeof RegistroRouteWithChildren
  RestablecerContrasenaRoute: typeof RestablecerContrasenaRoute
  PagoExitoRoute: typeof PagoExitoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iniciar-sesion': {
      id: '/iniciar-sesion'
      path: '/iniciar-sesion'
      fullPath: '/iniciar-sesion'
      preLoaderRoute: typeof IniciarSesionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-contrasena': {
      id: '/recuperar-contrasena'
      path: '/recuperar-contrasena'
      fullPath: '/recuperar-contrasena'
      preLoaderRoute: typeof RecuperarContrasenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restablecer-contrasena': {
      id: '/restablecer-contrasena'
      path: '/restablecer-contrasena'
      fullPath: '/restablecer-contrasena'
      preLoaderRoute: typeof RestablecerContrasenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cancelaciones': {
      id: '/admin/cancelaciones'
      path: '/cancelaciones'
      fullPath: '/admin/cancelaciones'
      preLoaderRoute: typeof AdminCancelacionesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finanzas': {
      id: '/admin/finanzas'
      path: '/finanzas'
      fullPath: '/admin/finanzas'
      preLoaderRoute: typeof AdminFinanzasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/planes': {
      id: '/admin/planes'
      path: '/planes'
      fullPath: '/admin/planes'
      preLoaderRoute: typeof AdminPlanesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/soporte': {
      id: '/admin/soporte'
      path: '/soporte'
      fullPath: '/admin/soporte'
      preLoaderRoute: typeof AdminSoporteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/eventos/': {
      id: '/eventos/'
      path: '/'
      fullPath: '/eventos/'
      preLoaderRoute: typeof EventosIndexRouteImport
      parentRoute: typeof EventosRoute
    }
    '/eventos/$eventId': {
      id: '/eventos/$eventId'
      path: '/$eventId'
      fullPath: '/eventos/$eventId'
      preLoaderRoute: typeof EventosEventIdRouteImport
      parentRoute: typeof EventosRoute
    }
    '/eventos/nuevo': {
      id: '/eventos/nuevo'
      path: '/nuevo'
      fullPath: '/eventos/nuevo'
      preLoaderRoute: typeof EventosNuevoRouteImport
      parentRoute: typeof EventosRoute
    }
    '/eventos/soporte': {
      id: '/eventos/soporte'
      path: '/soporte'
      fullPath: '/eventos/soporte'
      preLoaderRoute: typeof EventosSoporteRouteImport
      parentRoute: typeof EventosRoute
    }
    '/eventos/suscripcion': {
      id: '/eventos/suscripcion'
      path: '/suscripcion'
      fullPath: '/eventos/suscripcion'
      preLoaderRoute: typeof EventosSuscripcionRouteImport
      parentRoute: typeof EventosRoute
    }
    '/eventos/whatsapp': {
      id: '/eventos/whatsapp'
      path: '/whatsapp'
      fullPath: '/eventos/whatsapp'
      preLoaderRoute: typeof EventosWhatsappRouteImport
      parentRoute: typeof EventosRoute
    }
    '/pago/exito': {
      id: '/pago/exito'
      path: '/pago/exito'
      fullPath: '/pago/exito'
      preLoaderRoute: typeof PagoExitoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro/exito': {
      id: '/registro/exito'
      path: '/exito'
      fullPath: '/registro/exito'
      preLoaderRoute: typeof RegistroExitoRouteImport
      parentRoute: typeof RegistroRoute
    }
    '/admin/soporte/': {
      id: '/admin/soporte/'
      path: '/'
      fullPath: '/admin/soporte/'
      preLoaderRoute: typeof AdminSoporteIndexRouteImport
      parentRoute: typeof AdminSoporteRoute
    }
    '/admin/soporte/$ticketId': {
      id: '/admin/soporte/$ticketId'
      path: '/$ticketId'
      fullPath: '/admin/soporte/$ticketId'
      preLoaderRoute: typeof AdminSoporteTicketIdRouteImport
      parentRoute: typeof AdminSoporteRoute
    }
    '/eventos/$eventId/': {
      id: '/eventos/$eventId/'
      path: '/'
      fullPath: '/eventos/$eventId/'
      preLoaderRoute: typeof EventosEventIdIndexRouteImport
      parentRoute: typeof EventosEventIdRoute
    }
    '/eventos/$eventId/automatizacion': {
      id: '/eventos/$eventId/automatizacion'
      path: '/automatizacion'
      fullPath: '/eventos/$eventId/automatizacion'
      preLoaderRoute: typeof EventosEventIdAutomatizacionRouteImport
      parentRoute: typeof EventosEventIdRoute
    }
    '/eventos/$eventId/configuracion': {
      id: '/eventos/$eventId/configuracion'
      path: '/configuracion'
      fullPath: '/eventos/$eventId/configuracion'
      preLoaderRoute: typeof EventosEventIdConfiguracionRouteImport
      parentRoute: typeof EventosEventIdRoute
    }
    '/eventos/$eventId/conversaciones': {
      id: '/eventos/$eventId/conversaciones'
      path: '/conversaciones'
      fullPath: '/eventos/$eventId/conversaciones'
      preLoaderRoute: typeof EventosEventIdConversacionesRouteImport
      parentRoute: typeof EventosEventIdRoute
    }
    '/eventos/$eventId/estadisticas': {
      id: '/eventos/$eventId/estadisticas'
      path: '/estadisticas'
      fullPath: '/eventos/$eventId/estadisticas'
      preLoaderRoute: typeof EventosEventIdEstadisticasRouteImport
      parentRoute: typeof EventosEventIdRoute
    }
    '/eventos/$eventId/importar': {
      id: '/eventos/$eventId/importar'
      path: '/importar'
      fullPath: '/eventos/$eventId/importar'
      preLoaderRoute: typeof EventosEventIdImportarRouteImport
      parentRoute: typeof EventosEventIdRoute
    }
    '/eventos/$eventId/invitados': {
      id: '/eventos/$eventId/invitados'
      path: '/invitados'
      fullPath: '/eventos/$eventId/invitados'
      preLoaderRoute: typeof EventosEventIdInvitadosRouteImport
      parentRoute: typeof EventosEventIdRoute
    }
    '/eventos/$eventId/lista-final': {
      id: '/eventos/$eventId/lista-final'
      path: '/lista-final'
      fullPath: '/eventos/$eventId/lista-final'
      preLoaderRoute: typeof EventosEventIdListaFinalRouteImport
      parentRoute: typeof EventosEventIdRoute
    }
    '/eventos/$eventId/mensajes': {
      id: '/eventos/$eventId/mensajes'
      path: '/mensajes'
      fullPath: '/eventos/$eventId/mensajes'
      preLoaderRoute: typeof EventosEventIdMensajesRouteImport
      parentRoute: typeof EventosEventIdRoute
    }
    '/eventos/$eventId/resumen': {
      id: '/eventos/$eventId/resumen'
      path: '/resumen'
      fullPath: '/eventos/$eventId/resumen'
      preLoaderRoute: typeof EventosEventIdResumenRouteImport
      parentRoute: typeof EventosEventIdRoute
    }
    '/eventos/soporte/': {
      id: '/eventos/soporte/'
      path: '/'
      fullPath: '/eventos/soporte/'
      preLoaderRoute: typeof EventosSoporteIndexRouteImport
      parentRoute: typeof EventosSoporteRoute
    }
    '/eventos/soporte/$ticketId': {
      id: '/eventos/soporte/$ticketId'
      path: '/$ticketId'
      fullPath: '/eventos/soporte/$ticketId'
      preLoaderRoute: typeof EventosSoporteTicketIdRouteImport
      parentRoute: typeof EventosSoporteRoute
    }
  }
}

interface AdminSoporteRouteChildren {
  AdminSoporteTicketIdRoute: typeof AdminSoporteTicketIdRoute
  AdminSoporteIndexRoute: typeof AdminSoporteIndexRoute
}

const AdminSoporteRouteChildren: AdminSoporteRouteChildren = {
  AdminSoporteTicketIdRoute: AdminSoporteTicketIdRoute,
  AdminSoporteIndexRoute: AdminSoporteIndexRoute,
}

const AdminSoporteRouteWithChildren = AdminSoporteRoute._addFileChildren(
  AdminSoporteRouteChildren,
)

interface AdminRouteChildren {
  AdminCancelacionesRoute: typeof AdminCancelacionesRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminFinanzasRoute: typeof AdminFinanzasRoute
  AdminPlanesRoute: typeof AdminPlanesRoute
  AdminSoporteRoute: typeof AdminSoporteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCancelacionesRoute: AdminCancelacionesRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminFinanzasRoute: AdminFinanzasRoute,
  AdminPlanesRoute: AdminPlanesRoute,
  AdminSoporteRoute: AdminSoporteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EventosEventIdRouteChildren {
  EventosEventIdAutomatizacionRoute: typeof EventosEventIdAutomatizacionRoute
  EventosEventIdConfiguracionRoute: typeof EventosEventIdConfiguracionRoute
  EventosEventIdConversacionesRoute: typeof EventosEventIdConversacionesRoute
  EventosEventIdEstadisticasRoute: typeof EventosEventIdEstadisticasRoute
  EventosEventIdImportarRoute: typeof EventosEventIdImportarRoute
  EventosEventIdInvitadosRoute: typeof EventosEventIdInvitadosRoute
  EventosEventIdListaFinalRoute: typeof EventosEventIdListaFinalRoute
  EventosEventIdMensajesRoute: typeof EventosEventIdMensajesRoute
  EventosEventIdResumenRoute: typeof EventosEventIdResumenRoute
  EventosEventIdIndexRoute: typeof EventosEventIdIndexRoute
}

const EventosEventIdRouteChildren: EventosEventIdRouteChildren = {
  EventosEventIdAutomatizacionRoute: EventosEventIdAutomatizacionRoute,
  EventosEventIdConfiguracionRoute: EventosEventIdConfiguracionRoute,
  EventosEventIdConversacionesRoute: EventosEventIdConversacionesRoute,
  EventosEventIdEstadisticasRoute: EventosEventIdEstadisticasRoute,
  EventosEventIdImportarRoute: EventosEventIdImportarRoute,
  EventosEventIdInvitadosRoute: EventosEventIdInvitadosRoute,
  EventosEventIdListaFinalRoute: EventosEventIdListaFinalRoute,
  EventosEventIdMensajesRoute: EventosEventIdMensajesRoute,
  EventosEventIdResumenRoute: EventosEventIdResumenRoute,
  EventosEventIdIndexRoute: EventosEventIdIndexRoute,
}

const EventosEventIdRouteWithChildren = EventosEventIdRoute._addFileChildren(
  EventosEventIdRouteChildren,
)

interface EventosSoporteRouteChildren {
  EventosSoporteTicketIdRoute: typeof EventosSoporteTicketIdRoute
  EventosSoporteIndexRoute: typeof EventosSoporteIndexRoute
}

const EventosSoporteRouteChildren: EventosSoporteRouteChildren = {
  EventosSoporteTicketIdRoute: EventosSoporteTicketIdRoute,
  EventosSoporteIndexRoute: EventosSoporteIndexRoute,
}

const EventosSoporteRouteWithChildren = EventosSoporteRoute._addFileChildren(
  EventosSoporteRouteChildren,
)

interface EventosRouteChildren {
  EventosEventIdRoute: typeof EventosEventIdRouteWithChildren
  EventosNuevoRoute: typeof EventosNuevoRoute
  EventosSoporteRoute: typeof EventosSoporteRouteWithChildren
  EventosSuscripcionRoute: typeof EventosSuscripcionRoute
  EventosWhatsappRoute: typeof EventosWhatsappRoute
  EventosIndexRoute: typeof EventosIndexRoute
}

const EventosRouteChildren: EventosRouteChildren = {
  EventosEventIdRoute: EventosEventIdRouteWithChildren,
  EventosNuevoRoute: EventosNuevoRoute,
  EventosSoporteRoute: EventosSoporteRouteWithChildren,
  EventosSuscripcionRoute: EventosSuscripcionRoute,
  EventosWhatsappRoute: EventosWhatsappRoute,
  EventosIndexRoute: EventosIndexRoute,
}

const EventosRouteWithChildren =
  EventosRoute._addFileChildren(EventosRouteChildren)

interface RegistroRouteChildren {
  RegistroExitoRoute: typeof RegistroExitoRoute
}

const RegistroRouteChildren: RegistroRouteChildren = {
  RegistroExitoRoute: RegistroExitoRoute,
}

const RegistroRouteWithChildren = RegistroRoute._addFileChildren(
  RegistroRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  EventosRoute: EventosRouteWithChildren,
  IniciarSesionRoute: IniciarSesionRoute,
  RecuperarContrasenaRoute: RecuperarContrasenaRoute,
  RegistroRoute: RegistroRouteWithChildren,
  RestablecerContrasenaRoute: RestablecerContrasenaRoute,
  PagoExitoRoute: PagoExitoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
